
# Names of the cameras to be rendered. If empty all cameras will be rendered
string[] cameras
# Wall time at which the request was created
float64 request_time
---
RenderedCameras render_result
# Wall time at which the response was completed
float64 response_time
