# JointGroupPositionController for the arm, allows to set the position of the joints
panda_arm_effort_effort_compensated_controller:
    type: gazebo_gym_utils/GravityCompensatedEffortController
    joint_chain:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
        - panda_joint8
    gravity_acceleration: 9.80665
