cartpole_v0:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30

  # Effort Controllers ---------------------------------------
  pole_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: cartpole_joint
    pid: {p: 1, i: 0.01, d: 0.01}

  foot_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: foot_joint
    pid: {p: 1000.0, i: 0.0, d: 0.0}